/**
 * GENERATED BY /build-website SKILL — DO NOT EDIT MANUALLY
 *
 * Keyed by the same slugs defined in LOCATIONS array in src/config/site.ts.
 */

import type { LocationContent } from "../types/content";
import { CONTENT_PLACEHOLDER } from "../types/content";

export const LOCATIONS_CONTENT: Record<string, LocationContent> = {
  _placeholder: CONTENT_PLACEHOLDER,
};
