/**
 * GENERATED BY /build-website SKILL — DO NOT EDIT MANUALLY
 *
 * This file is overwritten on each client build with Rankability-generated content.
 * Keyed by the same slugs defined in SERVICES array in src/config/site.ts.
 *
 * Shape: Record<slug, ServiceContent>
 * See: src/types/content.ts
 */

import type { ServiceContent } from "../types/content";
import { CONTENT_PLACEHOLDER } from "../types/content";

export const SERVICES_CONTENT: Record<string, ServiceContent> = {
  // Populated by /build-website skill via Rankability API.
  // Each key matches a slug from the SERVICES array in src/config/site.ts.
  // Example structure (replaced on build):
  //
  // "bathroom-remodeling": {
  //   seoTitle:        "Bathroom Remodeling Plano TX | HAWC General Contracting",
  //   metaDescription: "Expert bathroom remodeling in Plano, TX...",
  //   h1:              "Expert Bathroom Remodeling in Plano, TX",
  //   bodyHtml:        "<h2>...</h2>...",
  //   faqs:            [{ question: "...", answer: "..." }],
  //   faqSchemaJsonLd: "{...}",
  // },
  _placeholder: CONTENT_PLACEHOLDER,
};
